#!/usr/bin/env bash
# ============================================================
# setup-test-server.sh
#
# One-shot setup for the court-platform test deployment on a
# Hetzner Ubuntu 22.04 server provisioned by the temp-infra
# Terraform stack. Idempotent — safe to re-run.
#
# What cloud-init already gave us:
#   - Docker Engine + buildx + compose-plugin
#   - nginx (systemd service, listening on :80)
#   - ufw  (22/80/443 allowed)
#   - fail2ban, unattended-upgrades
#
# What this script adds:
#   - certbot + python3-certbot-nginx
#   - .env.test with strong random DB_PASSWORD + SLA_JWT_SECRET
#     (generated once; never overwritten)
#   - docker-compose.override.server.yml that pins the frontend
#     container to 127.0.0.1:8080 (reachable only via host nginx)
#   - /etc/nginx/sites-available/test.kubetrust.com (reverse proxy)
#   - Let's Encrypt cert for test.kubetrust.com
#
# Prerequisites:
#   1. Copy docker-compose.test.yml into the same directory as
#      this script before running.
#   2. DNS for test.kubetrust.com must already resolve to this
#      server's public IPv4 (Let's Encrypt will fail otherwise).
#   3. Run as a sudoer (the `fadi` user works — NOPASSWD sudo).
#
# Usage:
#   bash setup-test-server.sh
#   bash setup-test-server.sh --email you@example.com   (skip prompt)
#   bash setup-test-server.sh --staging                 (test cert only)
# ============================================================

set -euo pipefail

# ---------- config ----------
DOMAIN="test.kubetrust.com"
HOST_PORT="8080"                              # frontend container binds here on 127.0.0.1
COMPOSE_FILE="docker-compose.test.yml"
OVERRIDE_FILE="docker-compose.override.server.yml"
ENV_FILE=".env.test"
NGINX_SITE="/etc/nginx/sites-available/${DOMAIN}"
NGINX_LINK="/etc/nginx/sites-enabled/${DOMAIN}"

# ---------- args ----------
CERTBOT_EMAIL=""
CERTBOT_STAGING=""
for arg in "$@"; do
  case "$arg" in
    --email=*)  CERTBOT_EMAIL="${arg#--email=}" ;;
    --email)    shift; CERTBOT_EMAIL="${1:-}" ;;
    --staging)  CERTBOT_STAGING="--staging" ;;
    -h|--help)
      sed -n '2,40p' "$0"; exit 0 ;;
  esac
done

# ---------- helpers ----------
log()  { printf '\n\033[1;36m==>\033[0m %s\n' "$*"; }
ok()   { printf '    \033[1;32m✓\033[0m %s\n' "$*"; }
warn() { printf '    \033[1;33m!\033[0m %s\n' "$*"; }
die()  { printf '\n\033[1;31m✗\033[0m %s\n' "$*" >&2; exit 1; }

# Generate a base64 random string (for JWT/DB secrets)
gen_secret() { openssl rand -base64 "$1" | tr -d '\n='; }

# ---------- step 1: pre-flight ----------
log "Pre-flight checks"

[[ $EUID -ne 0 ]] && ! sudo -n true 2>/dev/null && die "Need sudo without password prompt."

[[ -f "$COMPOSE_FILE" ]] || die "$COMPOSE_FILE not found in $(pwd). Copy it here first."

command -v docker  >/dev/null 2>&1 || die "docker not installed (expected from cloud-init)."
docker compose version >/dev/null 2>&1 || die "docker compose plugin missing."
command -v nginx   >/dev/null 2>&1 || die "nginx not installed (expected from cloud-init)."

# Check DNS resolves to this box
SERVER_IP="$(curl -fsS4 https://api.ipify.org || true)"
DNS_IP="$(getent hosts "$DOMAIN" | awk '{print $1}' | head -n1 || true)"
if [[ -z "$SERVER_IP" ]]; then
  warn "Couldn't detect public IP via ipify. Skipping DNS check."
elif [[ -z "$DNS_IP" ]]; then
  die "DNS for $DOMAIN does not resolve. Point it to $SERVER_IP and re-run."
elif [[ "$DNS_IP" != "$SERVER_IP" ]]; then
  warn "DNS for $DOMAIN resolves to $DNS_IP but this server is $SERVER_IP."
  warn "Let's Encrypt will fail until DNS propagates. Continuing anyway."
else
  ok "DNS: $DOMAIN → $SERVER_IP"
fi

ok "Pre-flight OK."

# ---------- step 2: install certbot if missing ----------
log "Ensuring certbot is installed"
if ! command -v certbot >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo apt-get install -y -qq certbot python3-certbot-nginx
  ok "Installed certbot + nginx plugin."
else
  ok "certbot already installed."
fi

# ---------- step 3: .env.test (never overwrite) ----------
log "Preparing ${ENV_FILE}"
if [[ -f "$ENV_FILE" ]]; then
  ok "${ENV_FILE} already exists — leaving untouched."
else
  DB_PW="$(gen_secret 24)"
  JWT_SECRET="$(gen_secret 48)"
  ADMIN_PW="ChangeMe!2026"
  cat > "$ENV_FILE" <<EOF
# Auto-generated by setup-test-server.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT commit this file. Back it up somewhere safe.

DB_NAME=sla_test
DB_USER=sla
DB_PASSWORD=${DB_PW}

SLA_JWT_SECRET=${JWT_SECRET}
SLA_BOOTSTRAP_ADMIN_PASSWORD=${ADMIN_PW}

# Frontend container binds to localhost only; host nginx reverse-proxies 443 → 127.0.0.1:8080
TEST_PORT=127.0.0.1:${HOST_PORT}
EOF
  chmod 600 "$ENV_FILE"
  ok "Generated ${ENV_FILE} (mode 600)."
  warn "Admin password on first login: ${ADMIN_PW}  (change it immediately!)"
fi

# ---------- step 4: compose override (pin frontend to localhost) ----------
log "Writing compose override (${OVERRIDE_FILE})"
cat > "$OVERRIDE_FILE" <<EOF
# Pins the frontend container to 127.0.0.1:${HOST_PORT} so host nginx is the
# only public-facing surface. Generated by setup-test-server.sh — safe to edit.
services:
  frontend:
    ports:
      - "127.0.0.1:${HOST_PORT}:80"
EOF
ok "Wrote ${OVERRIDE_FILE}."

# ---------- step 5: docker login reminder ----------
# Images are public on Docker Hub so no login required, just noting.
log "Pulling images"
sudo docker compose \
  -f "$COMPOSE_FILE" -f "$OVERRIDE_FILE" \
  --env-file "$ENV_FILE" pull
ok "Images pulled."

# ---------- step 6: start the stack ----------
log "Starting docker compose stack"
sudo docker compose \
  -f "$COMPOSE_FILE" -f "$OVERRIDE_FILE" \
  --env-file "$ENV_FILE" up -d
ok "Stack is up."

# Wait for backend to become healthy (up to 3 min)
log "Waiting for backend health (up to 180s)"
for i in {1..36}; do
  STATUS=$(sudo docker inspect --format='{{.State.Health.Status}}' \
    "$(sudo docker compose -f "$COMPOSE_FILE" -f "$OVERRIDE_FILE" --env-file "$ENV_FILE" ps -q backend)" 2>/dev/null || echo "starting")
  case "$STATUS" in
    healthy) ok "Backend healthy after $((i*5))s."; break ;;
    unhealthy) die "Backend reported unhealthy. Check: sudo docker compose -f $COMPOSE_FILE -f $OVERRIDE_FILE --env-file $ENV_FILE logs backend" ;;
  esac
  sleep 5
  [[ $i -eq 36 ]] && warn "Backend not yet healthy after 3 min — proceeding, but certbot may run before it's serving."
done

# ---------- step 7: nginx site (plain HTTP for now; certbot adds TLS) ----------
log "Configuring nginx site for ${DOMAIN}"
sudo tee "$NGINX_SITE" >/dev/null <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    # Bigger attachments (frontend image has 55m too)
    client_max_body_size 55m;
    proxy_read_timeout 120s;

    location / {
        proxy_pass         http://127.0.0.1:${HOST_PORT};
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_set_header   Upgrade           \$http_upgrade;
        proxy_set_header   Connection        "upgrade";
    }
}
EOF

# Remove the default site if enabled
if [[ -L /etc/nginx/sites-enabled/default ]]; then
  sudo rm -f /etc/nginx/sites-enabled/default
  ok "Removed default nginx site."
fi

# Enable our site
sudo ln -sf "$NGINX_SITE" "$NGINX_LINK"
sudo nginx -t >/dev/null
sudo systemctl reload nginx
ok "Nginx reloaded with ${DOMAIN} site."

# ---------- step 8: Let's Encrypt cert ----------
log "Provisioning Let's Encrypt TLS cert"

# If cert already exists, let certbot auto-renew handle it
if sudo test -d "/etc/letsencrypt/live/${DOMAIN}"; then
  ok "Cert for ${DOMAIN} already exists — skipping issuance."
else
  # Prompt for email if not set
  if [[ -z "$CERTBOT_EMAIL" ]]; then
    read -r -p "    Email for Let's Encrypt notifications (or leave blank for --register-unsafely-without-email): " CERTBOT_EMAIL || true
  fi
  EMAIL_FLAG=""
  if [[ -n "$CERTBOT_EMAIL" ]]; then
    EMAIL_FLAG="--email $CERTBOT_EMAIL --no-eff-email"
  else
    EMAIL_FLAG="--register-unsafely-without-email"
  fi

  sudo certbot --nginx \
    -d "$DOMAIN" \
    --agree-tos \
    --redirect \
    --non-interactive \
    $EMAIL_FLAG \
    $CERTBOT_STAGING
  ok "TLS cert installed. nginx now serves HTTPS on ${DOMAIN}."
fi

# Enable certbot auto-renewal timer (should already be enabled post-install)
sudo systemctl enable --now certbot.timer >/dev/null 2>&1 || true

# ---------- step 9: final verification ----------
log "Verifying end-to-end"
SCHEME="https"
[[ -n "$CERTBOT_STAGING" ]] && SCHEME="http"

HTTP_CODE=$(curl -fsS -o /dev/null -w '%{http_code}' -L "$SCHEME://${DOMAIN}/" || echo "000")
API_CODE=$(curl -fsS -o /dev/null -w '%{http_code}' -L "$SCHEME://${DOMAIN}/api/v3/api-docs" || echo "000")

case "$HTTP_CODE" in
  200|301|302) ok "Frontend reachable at $SCHEME://${DOMAIN}/ (HTTP $HTTP_CODE)" ;;
  *)           warn "Frontend returned HTTP $HTTP_CODE — check nginx + compose logs." ;;
esac
case "$API_CODE" in
  200)        ok "Backend reachable at $SCHEME://${DOMAIN}/api/ (HTTP $API_CODE)" ;;
  *)          warn "Backend returned HTTP $API_CODE — check backend logs." ;;
esac

# ---------- summary ----------
cat <<EOF

============================================================
✓ Setup complete.
============================================================

  URL       : https://${DOMAIN}/
  Login     : admin  /  $(grep '^SLA_BOOTSTRAP_ADMIN_PASSWORD=' "$ENV_FILE" | cut -d= -f2-)
  Env file  : $(pwd)/${ENV_FILE}   (keep this safe!)

Watch the user activity stream during a test session:

  sudo docker compose \\
    -f ${COMPOSE_FILE} -f ${OVERRIDE_FILE} --env-file ${ENV_FILE} \\
    logs -f backend | grep -E '\[ACTION\]|\[DENIED\]|\[FAILED\]|\[SYSTEM\]'

Stop the stack (keeps data):

  sudo docker compose \\
    -f ${COMPOSE_FILE} -f ${OVERRIDE_FILE} --env-file ${ENV_FILE} down

Upgrade to a new image tag (edit ${COMPOSE_FILE}, then):

  sudo docker compose \\
    -f ${COMPOSE_FILE} -f ${OVERRIDE_FILE} --env-file ${ENV_FILE} pull
  sudo docker compose \\
    -f ${COMPOSE_FILE} -f ${OVERRIDE_FILE} --env-file ${ENV_FILE} up -d

Renew TLS cert manually (auto-renewal already scheduled):

  sudo certbot renew --dry-run

============================================================
EOF
